.TH "ncic" 1
.SH NAME
ncic \- A naken chat client for the UNIX console based on pork.
.SH VERSION
.TP
.B version 0.2
.SH SYNOPSIS
.B ncic
.SH DESCRIPTION
NCIC is a chat client for Michael Kohn's Nakenchat (www.naken.cc).
NCIC stands for either Naken Chat in Curses or Naken Chat in Color,
you pick. It is heavily based on Pork (http://dev.ojnk.org) which was
written by Ryan McGabe

NCIC was written by Devin Smith
.SH OPTIONS
.TP
None as yet.
.SH FILES
.TP
.B ~/.ncic/ncic
\- The ncic configuration file
.SH BUGS
.TP
.B devin@devinsmith.net 
\- Please report bugs to this address
.SH HOMEPAGE
.TP
.B http://devinsmith.net
